title: .
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0
  lightness: 0.1025778
  brandColors:
    - '#202020'
    - '#E2E2E2'
    - '#9B9DA3'
    - '#007AFF'
    - '#4CD964'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Priesthood
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2153598
layout_spectrum: 1
