title: .
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.03061223
  lightness: 0.1025778
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#ababab'
    - '#383838'
    - '#6e6e6e'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Priesthood
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2153598
layout_spectrum: 0.9897959
