title: .
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0
  lightness: 0.1025778
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#282828'
    - '#BDBDBD'
    - '#4A4A4A'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Priesthood
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2153598
layout_spectrum: 1
